language: c
compiler:
  - clang
  - gcc
cache:
  - ccache
addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
# branches safelist
branches:
  only:
    - master
    - develop
before_script:
  - scan-build cmake .
script:
  - scan-build --status-bugs make -j -k
  - make test
